In [8]:
library(data.table)
library(tidyverse)
library(ggplot2)

In [9]:
computeRepIndex=function(allreads,valuevar){
    print(allreads)
    DTsam = allreads %>% spread(strand,valuevar,fill = 0)
#    DTsam=dcast.data.table(allreads,CBC+sample+datalabel~strand,value.var = valuevar,fill=0)
    DTsam = DTsam %>% mutate(readSum=(as.numeric(Negative)+as.numeric(Positive)))
    DTsam = DTsam %>% mutate(repIndex=(as.numeric(Negative)/readSum))
    DTsam = DTsam %>% mutate(DataTable=valuevar)
    return(DTsam)
}

In [10]:
THEME=theme_classic()
CUTOFF=100
#data.table version

In [11]:
"Viral Samples, with virus-specific primers in two orientations, head-to-head or tail-to-tail"

[1] "Viral Samples, with virus-specific primers in two orientations, head-to-head or tail-to-tail"

In [12]:
EV71=readr::read_rds(file = "EV71_SCISSORS.rds")
#CVB=readr::read_rds(file = "CVB_SCISSORS.rds")
#PV=readr::read_rds(file = "PV_SCISSORS.rds")

Warning message in readRDS(con, refhook = refhook):
“cannot open file 'EV71_SCISSORS.rds': No such file or directory”

ERROR: Error in readRDS(con, refhook = refhook): cannot open the connection

In [57]:
#CVBDT=computeRepIndex(CVB,"CVB3_RNA")
EV71
EV71DT=computeRepIndex(EV71,"pUC19-EV71-TW_Tainan_1998_4643_BsmBI-and-BsaI-free-Deleted")

       ...1
1      VH01023:1:AAC2L5HM5:1:1101:20882:1038:GTACACCAGTTCGCATCCCACTGACC
2      VH01023:1:AAC2L5HM5:1:1101:60552:1473:GAACCTACAAGGACTGCTCTAAGGGG
3      VH01023:1:AAC2L5HM5:1:1101:47032:1511:CGAGCACTCTCTTGATTGATTTACAT
4      VH01023:1:AAC2L5HM5:1:1101:21507:1587:CGAGCACTCTCTTGATGTAGCAGCTA
5      VH01023:1:AAC2L5HM5:1:1101:47752:1625:CTACACCAGTTCGCATCCAACGTATG
6      VH01023:1:AAC2L5HM5:1:1101:51955:1663:GTCCTCATCGGTGTCGTGTGTGTACA
7      VH01023:1:AAC2L5HM5:1:1101:49759:1966:ATCGAGTTCGACAGCCATGTGAGCCG
8      VH01023:1:AAC2L5HM5:1:1101:62824:1966:GATCGCGGTTAAAGTGTGATACCAGC
9      VH01023:1:AAC2L5HM5:1:1101:56481:2022:GTGAAGGAGCAAATCAGTCAGGCAGT
10     VH01023:1:AAC2L5HM5:1:1101:42942:2041:ATCGAGTTCGACAGCCGGACCGCTCG
11     VH01023:1:AAC2L5HM5:1:1101:56424:2117:GTGAAGGAGCAAATCAGTCAGGCAGT
12     VH01023:1:AAC2L5HM5:1:1101:33683:2136:ATCGAGTTCGACAGCCCTAATGCTTC
13     VH01023:1:AAC2L5HM5:1:1101:38682:2136:CCTTACGGTTGGACCCCACTCTTGCA
14     VH01023:1:AAC2L5HM5:1:1101:34648:2193:CTACACCAGTTCGCATATTCATCACA
15     VH01023:1:AAC2L5HM5:1:1101:21053:2268:GGCGACTCACTATCTTGGCCCCAGTA
16     VH01023:1:AAC2L5HM5:1:1101:26468:2306:CTACACCAGTTCGCATGCGTCGCTCT
17     VH01023:1:AAC2L5HM5:1:1101:26828:2401:GGCGACTCACTATCTTGCAACAGCGA
18     VH01023:1:AAC2L5HM5:1:1101:34667:2515:GATCTAGCAGACAAATTACAGTCCCG
19     VH01023:1:AAC2L5HM5:1:1101:28513:2571:ATCGAGTTCGACAGCCTACAGGGATA
20     VH01023:1:AAC2L5HM5:1:1101:26298:2704:TGGCCAGCATCACGTATGTTTCATTC
21     VH01023:1:AAC2L5HM5:1:1101:17000:2799:CGAGCACTCTCTTGATGTAGCAGCTA
22     VH01023:1:AAC2L5HM5:1:1101:44911:2799:GATTCAGGTGATGATAGCCGACAGCC
23     VH01023:1:AAC2L5HM5:1:1101:42374:2836:CTACACCAGTTCGCATGGCATAACGG
24     VH01023:1:AAC2L5HM5:1:1101:59927:3120:TCAGGTAGTAGGGACTTGCCATCTGG
25     VH01023:1:AAC2L5HM5:1:1101:26090:3139:GGCGACTCACTATCTTGCAACAGCGA
26     VH01023:1:AAC2L5HM5:1:1101:48945:3272:CAAGGCCCACCGAATTTATACGAATC
27     VH01023:1:AAC2L5HM5:1:1101:39041:3329:GGGTTGCCAGTAACGGTAACGGGTCG
28     VH01023:1:AAC2L5HM5:1:1101:22302:3480:TGGCCAGCATCACGTACATTACATCA
29     VH01023:1:AAC2L5HM5:1:1101:35860:3594:CATTATCGTATATCCGAGGGAGGAGT
30     VH01023:1:AAC2L5HM5:1:1101:66214:3650:AAGACCTGTGACTACTTAGGCTGAGA
⋮      ⋮
158420 VH01023:1:AAC2L5HM5:1:2504:40518:22109:CGAACATGTCTGCGGTCACAGGTCTT
158421 VH01023:1:AAC2L5HM5:1:2505:54947:47930:AGCCTAATCCTATTCACTATAGCGTC
158422 VH01023:1:AAC2L5HM5:1:2506:46445:27769:CCACGGATCAGTGTTGCGGTGACCTA
158423 VH01023:1:AAC2L5HM5:1:2506:68903:30344:TTATGCTTCCTTCAATCGCTAAGTCC
158424 VH01023:1:AAC2L5HM5:1:2506:49039:31536:TGAGCATGTCGCTTCTCTCGGGTTTT
158425 VH01023:1:AAC2L5HM5:1:2506:48358:53723:ATCATGGTCTTGTTTGCGATCGACGG
158426 VH01023:1:AAC2L5HM5:1:2507:26184:46473:GGGAGATCAAACCCATACCCTCCCCG
158427 VH01023:1:AAC2L5HM5:1:2508:71573:11091:CAAGGCCGTACTTAGCAGACGCTGGG
158428 VH01023:1:AAC2L5HM5:1:2508:46350:16884:GTCACGGAGAATTCCCCTTTCCATAA
158429 VH01023:1:AAC2L5HM5:1:2508:50497:29890:TGGCCAGGTACCGTTATCCGTCTGAA
158430 VH01023:1:AAC2L5HM5:1:2511:57295:23056:CTACATTAGTATCTCGGATCTGTTGC
158431 VH01023:1:AAC2L5HM5:1:2511:73712:23377:ACACTGAAGTCACGCCTCTGACCTTT
158432 VH01023:1:AAC2L5HM5:1:2511:33455:27845:CTACATTTCGTAGGTTCCTTCCGCGC
158433 VH01023:1:AAC2L5HM5:1:2511:19064:38295:GACCATTGCGTGGCCCACAAACTCTT
158434 VH01023:1:AAC2L5HM5:1:2601:13876:21636:CTGATCCTCTGTACGAGGTCAAAATT
158435 VH01023:1:AAC2L5HM5:1:2602:54190:22980:AGAGCTTGTAGTAGTAAAAAATGCGA
158436 VH01023:1:AAC2L5HM5:1:2602:59946:29151:CCTAAAGAGGCCATAGCTGGCAATCG
158437 VH01023:1:AAC2L5HM5:1:2603:52107:16240:GCTGCGACAGCCAGAACCTAGTCTTT
158438 VH01023:1:AAC2L5HM5:1:2603:8366:20670:CTAGTGACACCAGATTGTATCATCCC
158439 VH01023:1:AAC2L5HM5:1:2603:42639:52398:GGCGTGTGTCGTGGCTTTAATGAGCA
158440 VH01023:1:AAC2L5HM5:1:2604:67653:14858:TTCTCCTCACAGCCCACTTCTATTAC
158441 VH01023:1:AAC2L5HM5:1:2604:29006:45659:AGCTCCTAGCGATGACGTTGGGACCT
158442 VH01023:1:AAC2L5HM5:1:2605:60022:11015:ATTTCTGGTGTTAAGAGGCTTTAAGT
158443 VH01023:1:AAC2L5HM5:1:2607:61991:22715:ACCGTAACAATCTGCACGCGCCCTAG
158444 VH01023:1:AAC2L5HM5:1:2608:17531:5714:CAAGATCTCGCTTGTCCCAACCGGTG
158445 VH01023:1:AAC2L5HM5:1:2608:28949:10693:GGGCATCTCCGCTGTTACTGTGGATT
158446 VH01023:1:AAC2L5HM5:1:2610:20030:14309:CATATGGAGGACTGGTAGAACTAAAC
158447 VH01023:1:AAC2L5HM5:1:2610:41105:53629:GCCTCTAAGCATCATCGGCATTAGCC
158448 VH01023:1:AAC2L5HM5:1:2611:56973:10845:GAGACCATCCGGGTGTACGTAATTAG
158449 VH01023:1:AAC2L5HM5:1:2611:44779:33524:GCGCCGACACGCCAGTTTTACTCTGC
       name                                                              flag
1      VH01023:1:AAC2L5HM5:1:1101:20882:1038:GTACACCAGTTCGCATCCCACTGACC  16
2      VH01023:1:AAC2L5HM5:1:1101:60552:1473:GAACCTACAAGGACTGCTCTAAGGGG  16
3      VH01023:1:AAC2L5HM5:1:1101:47032:1511:CGAGCACTCTCTTGATTGATTTACAT  16
4      VH01023:1:AAC2L5HM5:1:1101:21507:1587:CGAGCACTCTCTTGATGTAGCAGCTA  16
5      VH01023:1:AAC2L5HM5:1:1101:47752:1625:CTACACCAGTTCGCATCCAACGTATG  16
6      VH01023:1:AAC2L5HM5:1:1101:51955:1663:GTCCTCATCGGTGTCGTGTGTGTACA  16
7      VH01023:1:AAC2L5HM5:1:1101:49759:1966:ATCGAGTTCGACAGCCATGTGAGCCG  16
8      VH01023:1:AAC2L5HM5:1:1101:62824:1966:GATCGCGGTTAAAGTGTGATACCAGC  16
9      VH01023:1:AAC2L5HM5:1:1101:56481:2022:GTGAAGGAGCAAATCAGTCAGGCAGT  16
10     VH01023:1:AAC2L5HM5:1:1101:42942:2041:ATCGAGTTCGACAGCCGGACCGCTCG  16
11     VH01023:1:AAC2L5HM5:1:1101:56424:2117:GTGAAGGAGCAAATCAGTCAGGCAGT  16
12     VH01023:1:AAC2L5HM5:1:1101:33683:2136:ATCGAGTTCGACAGCCCTAATGCTTC  16
13     VH01023:1:AAC2L5HM5:1:1101:38682:2136:CCTTACGGTTGGACCCCACTCTTGCA  16
14     VH01023:1:AAC2L5HM5:1:1101:34648:2193:CTACACCAGTTCGCATATTCATCACA  16
15     VH01023:1:AAC2L5HM5:1:1101:21053:2268:GGCGACTCACTATCTTGGCCCCAGTA  16
16     VH01023:1:AAC2L5HM5:1:1101:26468:2306:CTACACCAGTTCGCATGCGTCGCTCT  16
17     VH01023:1:AAC2L5HM5:1:1101:26828:2401:GGCGACTCACTATCTTGCAACAGCGA  16
18     VH01023:1:AAC2L5HM5:1:1101:34667:2515:GATCTAGCAGACAAATTACAGTCCCG  16
19     VH01023:1:AAC2L5HM5:1:1101:28513:2571:ATCGAGTTCGACAGCCTACAGGGATA  16
20     VH01023:1:AAC2L5HM5:1:1101:26298:2704:TGGCCAGCATCACGTATGTTTCATTC  16
21     VH01023:1:AAC2L5HM5:1:1101:17000:2799:CGAGCACTCTCTTGATGTAGCAGCTA  16
22     VH01023:1:AAC2L5HM5:1:1101:44911:2799:GATTCAGGTGATGATAGCCGACAGCC  16
23     VH01023:1:AAC2L5HM5:1:1101:42374:2836:CTACACCAGTTCGCATGGCATAACGG  16
24     VH01023:1:AAC2L5HM5:1:1101:59927:3120:TCAGGTAGTAGGGACTTGCCATCTGG   0
25     VH01023:1:AAC2L5HM5:1:1101:26090:3139:GGCGACTCACTATCTTGCAACAGCGA  16
26     VH01023:1:AAC2L5HM5:1:1101:48945:3272:CAAGGCCCACCGAATTTATACGAATC  16
27     VH01023:1:AAC2L5HM5:1:1101:39041:3329:GGGTTGCCAGTAACGGTAACGGGTCG  16
28     VH01023:1:AAC2L5HM5:1:1101:22302:3480:TGGCCAGCATCACGTACATTACATCA  16
29     VH01023:1:AAC2L5HM5:1:1101:35860:3594:CATTATCGTATATCCGAGGGAGGAGT  16
30     VH01023:1:AAC2L5HM5:1:1101:66214:3650:AAGACCTGTGACTACTTAGGCTGAGA  16
⋮      ⋮                                                                 ⋮
158420 VH01023:1:AAC2L5HM5:1:2504:40518:22109:CGAACATGTCTGCGGTCACAGGTCTT 2064
158421 VH01023:1:AAC2L5HM5:1:2505:54947:47930:AGCCTAATCCTATTCACTATAGCGTC 2064
158422 VH01023:1:AAC2L5HM5:1:2506:46445:27769:CCACGGATCAGTGTTGCGGTGACCTA 2064
158423 VH01023:1:AAC2L5HM5:1:2506:68903:30344:TTATGCTTCCTTCAATCGCTAAGTCC 2064
158424 VH01023:1:AAC2L5HM5:1:2506:49039:31536:TGAGCATGTCGCTTCTCTCGGGTTTT 2048
158425 VH01023:1:AAC2L5HM5:1:2506:48358:53723:ATCATGGTCTTGTTTGCGATCGACGG 2048
158426 VH01023:1:AAC2L5HM5:1:2507:26184:46473:GGGAGATCAAACCCATACCCTCCCCG    0
158427 VH01023:1:AAC2L5HM5:1:2508:71573:11091:CAAGGCCGTACTTAGCAGACGCTGGG 2064
158428 VH01023:1:AAC2L5HM5:1:2508:46350:16884:GTCACGGAGAATTCCCCTTTCCATAA 2048
158429 VH01023:1:AAC2L5HM5:1:2508:50497:29890:TGGCCAGGTACCGTTATCCGTCTGAA 2064
158430 VH01023:1:AAC2L5HM5:1:2511:57295:23056:CTACATTAGTATCTCGGATCTGTTGC 2064
158431 VH01023:1:AAC2L5HM5:1:2511:73712:23377:ACACTGAAGTCACGCCTCTGACCTTT 2064
158432 VH01023:1:AAC2L5HM5:1:2511:33455:27845:CTACATTTCGTAGGTTCCTTCCGCGC 2064
158433 VH01023:1:AAC2L5HM5:1:2511:19064:38295:GACCATTGCGTGGCCCACAAACTCTT 2064
158434 VH01023:1:AAC2L5HM5:1:2601:13876:21636:CTGATCCTCTGTACGAGGTCAAAATT 2064
158435 VH01023:1:AAC2L5HM5:1:2602:54190:22980:AGAGCTTGTAGTAGTAAAAAATGCGA 2064
158436 VH01023:1:AAC2L5HM5:1:2602:59946:29151:CCTAAAGAGGCCATAGCTGGCAATCG 2064
158437 VH01023:1:AAC2L5HM5:1:2603:52107:16240:GCTGCGACAGCCAGAACCTAGTCTTT 2064
158438 VH01023:1:AAC2L5HM5:1:2603:8366:20670:CTAGTGACACCAGATTGTATCATCCC  2064
158439 VH01023:1:AAC2L5HM5:1:2603:42639:52398:GGCGTGTGTCGTGGCTTTAATGAGCA 2064
158440 VH01023:1:AAC2L5HM5:1:2604:67653:14858:TTCTCCTCACAGCCCACTTCTATTAC 2064
158441 VH01023:1:AAC2L5HM5:1:2604:29006:45659:AGCTCCTAGCGATGACGTTGGGACCT 2064
158442 VH01023:1:AAC2L5HM5:1:2605:60022:11015:ATTTCTGGTGTTAAGAGGCTTTAAGT 2064
158443 VH01023:1:AAC2L5HM5:1:2607:61991:22715:ACCGTAACAATCTGCACGCGCCCTAG 2064
158444 VH01023:1:AAC2L5HM5:1:2608:17531:5714:CAAGATCTCGCTTGTCCCAACCGGTG  2064
158445 VH01023:1:AAC2L5HM5:1:2608:28949:10693:GGGCATCTCCGCTGTTACTGTGGATT 2064
158446 VH01023:1:AAC2L5HM5:1:2610:20030:14309:CATATGGAGGACTGGTAGAACTAAAC 2064
158447 VH01023:1:AAC2L5HM5:1:2610:41105:53629:GCCTCTAAGCATCATCGGCATTAGCC 2064
158448 VH01023:1:AAC2L5HM5:1:2611:56973:10845:GAGACCATCCGGGTGTACGTAATTAG 2064
158449 VH01023:1:AAC2L5HM5:1:2611:44779:33524:GCGCCGACACGCCAGTTTTACTCTGC 2064
       ref_pos map_quality cigar         next_ref_name next_ref_pos length
1       557    60          89M           *             0            0
2      1971    60          89M           *             0            0
3      7227    60          89M           *             0            0
4      6160    60          90M           *             0            0
5      5752    60          90M           *             0            0
6      3052    60          89M           *             0            0
7      6493    60          89M           *             0            0
8      1855    58          90M           *             0            0
9      6151    60          90M           *             0            0
10     6850    57          90M           *             0            0
11     6151    60          90M           *             0            0
12     5795    60          89M           *             0            0
13     1914    60          90M           *             0            0
14     1562    60          90M           *             0            0
15     2426    60          90M           *             0            0
16     6062    60          90M           *             0            0
17     6835    60          90M           *             0            0
18     5572    60          90M           *             0            0
19     5867    60          90M           *             0            0
20     1343    60          89M           *             0            0
21     6160    60          90M           *             0            0
22     7316    60          90M           *             0            0
23     7211    60          90M           *             0            0
24     5071    60          87M           *             0            0
25     6835    60          90M           *             0            0
26     6083    60          90M           *             0            0
27     1800    60          90M           *             0            0
28     4550    60          90M           *             0            0
29     5455    60          90M           *             0            0
30     6037    60          90M           *             0            0
⋮      ⋮       ⋮           ⋮             ⋮             ⋮            ⋮
158420 7411    56          42H48M        *             0            0
158421 7411    60          48M42H        *             0            0
158422 7411    60          48M42H        *             0            0
158423 7411    57          48M42H        *             0            0
158424 7411    56          40H49M        *             0            0
158425 7411    60          41H48M        *             0            0
158426 7409    57          2S31M2I19M35S *             0            0
158427 7411    60          48M42H        *             0            0
158428 7411    60          41H48M        *             0            0
158429 7411    57          4H48M37H      *             0            0
158430 7411    60          48M42H        *             0            0
158431 7411    60          48M42H        *             0            0
158432 7411    57          48M42H        *             0            0
158433 7411    57          48M42H        *             0            0
158434 7411    60          48M42H        *             0            0
158435 7411    56          34H48M8H      *             0            0
158436 7411    57          48M42H        *             0            0
158437 7411    60          42H48M        *             0            0
158438 7411    60          48M42H        *             0            0
158439 7411    57          48M42H        *             0            0
158440 7411    60          3H48M39H      *             0            0
158441 7411    60          48M42H        *             0            0
158442 7411    57          7H48M35H      *             0            0
158443 7411    57          48M42H        *             0            0
158444 7411    57          48M42H        *             0            0
158445 7411    60          48M42H        *             0            0
158446 7411    57          4H48M38H      *             0            0
158447 7411    57          48M42H        *             0            0
158448 7411    60          48M42H        *             0            0
158449 7411    60          48M42H        *             0            0
       seq
1      GTCCGTGTTTCCTTTTATTCCTATATTGGCTGCTTATGGAGACAATCAAAGAGTTGTTACCATATAGCTATTGGATTGGCCATCCGGTG
2      TCAGAGCTGACCCTGGACGAAGTGGGCCATGGCAGTCCACCTTGTTGGGCCAGTTGTGCGGGTACTACACCCAATGGTCAGGATCACTG
3      ATGAAAAATTTGTGAGTGCAATCAGATCAGTTCCAATTGGAAAAGCATTGGCTATACCAAATTATGAGAATCTGAGAAGAAATTGGCTC
4      CAAGGAGGCGGCCTTACATTATGCCAACCAACTCAAGCAGTTAGATATCAAGACCACCAAGATGAGCATGGAGGATGCATGTTACGGCAC
5      GTATGGGTTTTTGAACCTTAGTGGTAAGCCCACTCACAGGACTATGATGTACAATTTCCCAACAAAAGCAGGACAGTGTGGTGGTGTTGT
6      TTATGACGGGTATCCCACATTCGGTGAACACAAACAGGAGAAAGACCTTGAATACGGGGCATGCCCAAACAACATGATGGGTACGTTCT
7      GTACTTGAGAATGACATTTGGGCACCTTTATGAAGCTTTCCACGCCAATCCAGGTACAATCACTGGTTCAGCTGTTGGGTGTAACCCAG
8      CCAGGTGGAGACCATTTTAGAGGTCAACAATGTACCTACGAATGCCACTAGCTTAATGGAGAGACTGCGCTTCCCGGTCTCAGCTCAAGC
9      CGAGTTTGTCAAGGAGGCGGCCTTACATTATGCCAACCAACTCAAGCAGTTAGATATCAAGACCACCAAGATGAGCATGGAGGATGCATG
10     CATTATTAGAACACTCCTGATTAAAACATTCAAAGGGATAGATCTAGATGAACTGAACATGGTGGCCTATGGGGATGATGTGTTGGCTAG
11     CGAGTTAGTCAAGGAGGCGGCCTTACATTATGCCAACCAACTCAAGCAGTTAGATATCAAGACCACCAAGATGAGCATGGAGGATGCATG
12     ATGATGTACAATTTCCCAACAAAAGCAGGACAGTGTGGTGGTGTTGTGACTGCCGTGGGTAAAGTGATTGGGATCCACATTGGTGGCAA
13     AGAGACTGCGCTTCCCGGTCTCAGCTCAAGCCGGGAAAGGTGAGCTATGTGCAGTGTTCAGAGCTGACCCTGGACGAAGTGGGCCATGGC
14     GATTCTGCCTTGAACCATTGTAACTTTGGTCTGCTGGTTGTGCCTATTAGCCCGTTAGATTATGACCAAGGTGCGACGCCAGTGATCCCC
15     ACAGGCACTATCCAGGGAGATAGGGTGGCAGATGTGATTGAGAGTTCTATAGGGGACAGTGTGAGCAGAGCCCTCACCCGAGCTCTACCG
16     GTGCTGACTAGTAAAGACCCAAGGCTGGAAGTTGACTTTGAACAGGCTCTTTTTTCAAAATACGTGGGGAACACGCTTCATGAACCCGAC
17     GATGATCAACAATATCATTATTAGAACACTCCTGATTAAAACATTCAAAGGGATAGATCTAGATGAACTGAACATGGTGGCCTACGGGGA
18     GGTAGTAGACGAACAAGGGGTTAACTTAGAGCTCACACTGGTAACGCTTGATACTAACGAAAAATTTAGAGACATCACAAGATTCATACC
19     ATCCACATTGGTGGCAACGGTAGGCAAGGTTTCTGCGCTGCCCTGAAGAGGGGATACTTTTGCAGTGAACAAGGTGAGATCCAATGGATG
20     GTCATTGGGACAGTGGCAGGTGGCACAGGGACGGAGGATAGCCACCCCCCTTATAAGCAGACTCAACCCGGTGCTGATGGCTTCGAATT
21     CAAGGAGGCGGCCTTACATTATGCCAACCAACTCAAGCAGTTAGATATCAAGACCACCAAGATGAGCATGGAGGATGCATGTTACGGCAC
22     GAATTGTTTTAAATTTACAGTTTGTAACTGAACCCCACCAGTAATCTGGTCGCGTTAATGACTGGTGGGGGTAAATTTGTTATAACCAGA
23     AACGGGAAAGAGGAGTATGAAAAATTTGTGAGTGCAATCAGATCAGTTCCAATTGGAAAAGCATTGGCTATACCAAATTATGAGAATCTG
24     CCCTAAATTTAGACCAATAAGGATTAGCTTAGAGGAGAAGCCCGCACCTGATGCTATTAGTGACTTATTAGCTAGTGTTGATAGTGA
25     GATGATCAACAATATCATTATTAGAACACTCCTGATTAAAACATTCAAAGGGATAGATCTAGATGAACTGAACATGGTGGCCTACGGGGA
26     AGGCTGGAAGTTGACTTTGAACAGGCTCTTTTTTCAAAATACGTGGGGAACACGCTTCATGAACCCGACGAGTTTGTCAAGGAGGCGGCC
27     ACCCCACCCCGTGTATCCATATACCCGGTGAAGTTAGAAACTTGCTAGAGCTATGCCAGGTGGAGACCATTTTAGAGGTCAACAATGTAC
28     CCTCCAGACCCAGACCACTTTGACGGATACAAACAACAGATCGTCACTGTTATGGACGACCTATGCCAAAACCCAGACGGGAAAGACATG
29     GGGCCACTTTACAATGTTAGGAGTGCGAGACCGCTTGGCTGTGCTCCCCAGACACTCCCAACCAGGAAAGACCATCTGGGTTGAACACAA
30     GTTCGAAGGCACTAAAGAGCCAGCAGTGCTGACTAGTAAAGACCCAAGGCTGGAAGTTGACTTTGAACAGGCTCTTTTTTCAAAATACGT
⋮      ⋮
158420 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158421 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158422 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158423 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158424 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158425 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158426 AGGCAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTAAAAAAAAAAAAAAAAAAAAAAAAACACCCAAAAAAAAAAAAAAAAAAAAAACA
158427 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158428 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158429 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158430 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158431 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158432 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158433 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158434 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158435 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158436 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158437 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158438 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158439 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158440 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158441 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158442 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158443 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158444 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158445 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158446 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158447 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158448 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158449 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
       qual
1      CCCCCCCCCC;CC;C--C;-CCCC-C--;;C-;;-C-C;-CCCCCC;CCCCC;;CC;C;CCCC;;CCCCCC;-C-;CC-;-C-C--CCC
2      CCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCC
3      CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
4      CCCCCCCCCCCCCCCCC;CCCCCCCCCC;CCCCCCCCCC-CCCCCCCC;C-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
5      CCCCCCC;CCC;C;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
6      CCCCCCCC;CCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCCCCCC;
7      CCCCC-CCCCCCCCCCCCCCCCCCCC-CCCCCCCC;CCCCCCC-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCC;;CCCC
8      CCCCCCCCCCCCC;CCCCCCCCCCCCCCC-C;CC-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CC;CC-CCCCCCCCCCCC
9      CCCCCCCCCCCCC;CCC;CCCC--CC-CCCC;CCC;CCCCCCC-C-CC-;C;CCCC-C-CCCCCCCC--CCCCCCCCCCCCCCCCC;CCC
10     CCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCC;CCCCCCC
11     CCCC-C-CCCCCCCCCCCCCCCC;CCC;CCCCCCC;CCC;C;CCC-;C;CC;CCCC;;--CCCCCCC-CCCCCCCCCCCCCCCCCCCCCC
12     CCCCCCCCCCCCCCCCCCCCCCC;;CCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCC;CCCCCCCCCCC-CCC;CCCCC
13     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
14     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCC
15     CCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCC-CCCCCCCCCCCCCCCC;CC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCC
16     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CC
17     CCCCC-CCC;CCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCC;C
18     C-CCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCC;CCCCCCC

# A tibble: 158,449 × 17
   ...1  name   flag ref_pos map_quality cigar next_ref_name next_ref_pos length
   <chr> <chr> <dbl>   <dbl>       <dbl> <chr> <chr>                <dbl>  <dbl>
 1 VH01… VH01…    16     557          60 89M   *                        0      0
 2 VH01… VH01…    16    1971          60 89M   *                        0      0
 3 VH01… VH01…    16    7227          60 89M   *                        0      0
 4 VH01… VH01…    16    6160          60 90M   *                        0      0
 5 VH01… VH01…    16    5752          60 90M   *                        0      0
 6 VH01… VH01…    16    3052          60 89M   *                        0      0
 7 VH01… VH01…    16    6493          60 89M   *                        0      0
 8 VH01… VH01…    16    1855          58 90M   *                        0      0
 9 VH01… VH01…    16    6151          60 90M   *                        0      0
10 VH01… VH01…    16    6850          57 90M   *                        0      0
# ℹ 158,439 more rows
# ℹ 8 more variables: seq <chr>, qual <chr>, CBC <chr>, sample <chr>,
#   datalabel <chr>, UMIcount <int>, strand <chr>,
#   `pUC19-EV71-TW_Tainan_1998_4643_BsmBI-and-BsaI-free-Deleted` <chr>

Warning message:
“There were 2 warnings in `mutate()`.
The first warning was:
ℹ In argument: `readSum = (as.numeric(Negative) + as.numeric(Positive))`.
Caused by warning:
! NAs introduced by coercion
ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning.”
Warning message:
“There was 1 warning in `mutate()`.
ℹ In argument: `repIndex = (as.numeric(Negative)/readSum)`.
Caused by warning:
! NAs introduced by coercion”

EV71DT

In [44]:
EV71DT

       ...1
1      VH01023:1:AAC2L5HM5:1:1101:20882:1038:GTACACCAGTTCGCATCCCACTGACC
2      VH01023:1:AAC2L5HM5:1:1101:60552:1473:GAACCTACAAGGACTGCTCTAAGGGG
3      VH01023:1:AAC2L5HM5:1:1101:47032:1511:CGAGCACTCTCTTGATTGATTTACAT
4      VH01023:1:AAC2L5HM5:1:1101:21507:1587:CGAGCACTCTCTTGATGTAGCAGCTA
5      VH01023:1:AAC2L5HM5:1:1101:47752:1625:CTACACCAGTTCGCATCCAACGTATG
6      VH01023:1:AAC2L5HM5:1:1101:51955:1663:GTCCTCATCGGTGTCGTGTGTGTACA
7      VH01023:1:AAC2L5HM5:1:1101:49759:1966:ATCGAGTTCGACAGCCATGTGAGCCG
8      VH01023:1:AAC2L5HM5:1:1101:62824:1966:GATCGCGGTTAAAGTGTGATACCAGC
9      VH01023:1:AAC2L5HM5:1:1101:56481:2022:GTGAAGGAGCAAATCAGTCAGGCAGT
10     VH01023:1:AAC2L5HM5:1:1101:42942:2041:ATCGAGTTCGACAGCCGGACCGCTCG
11     VH01023:1:AAC2L5HM5:1:1101:56424:2117:GTGAAGGAGCAAATCAGTCAGGCAGT
12     VH01023:1:AAC2L5HM5:1:1101:33683:2136:ATCGAGTTCGACAGCCCTAATGCTTC
13     VH01023:1:AAC2L5HM5:1:1101:38682:2136:CCTTACGGTTGGACCCCACTCTTGCA
14     VH01023:1:AAC2L5HM5:1:1101:34648:2193:CTACACCAGTTCGCATATTCATCACA
15     VH01023:1:AAC2L5HM5:1:1101:21053:2268:GGCGACTCACTATCTTGGCCCCAGTA
16     VH01023:1:AAC2L5HM5:1:1101:26468:2306:CTACACCAGTTCGCATGCGTCGCTCT
17     VH01023:1:AAC2L5HM5:1:1101:26828:2401:GGCGACTCACTATCTTGCAACAGCGA
18     VH01023:1:AAC2L5HM5:1:1101:34667:2515:GATCTAGCAGACAAATTACAGTCCCG
19     VH01023:1:AAC2L5HM5:1:1101:28513:2571:ATCGAGTTCGACAGCCTACAGGGATA
20     VH01023:1:AAC2L5HM5:1:1101:26298:2704:TGGCCAGCATCACGTATGTTTCATTC
21     VH01023:1:AAC2L5HM5:1:1101:17000:2799:CGAGCACTCTCTTGATGTAGCAGCTA
22     VH01023:1:AAC2L5HM5:1:1101:44911:2799:GATTCAGGTGATGATAGCCGACAGCC
23     VH01023:1:AAC2L5HM5:1:1101:42374:2836:CTACACCAGTTCGCATGGCATAACGG
24     VH01023:1:AAC2L5HM5:1:1101:59927:3120:TCAGGTAGTAGGGACTTGCCATCTGG
25     VH01023:1:AAC2L5HM5:1:1101:26090:3139:GGCGACTCACTATCTTGCAACAGCGA
26     VH01023:1:AAC2L5HM5:1:1101:48945:3272:CAAGGCCCACCGAATTTATACGAATC
27     VH01023:1:AAC2L5HM5:1:1101:39041:3329:GGGTTGCCAGTAACGGTAACGGGTCG
28     VH01023:1:AAC2L5HM5:1:1101:22302:3480:TGGCCAGCATCACGTACATTACATCA
29     VH01023:1:AAC2L5HM5:1:1101:35860:3594:CATTATCGTATATCCGAGGGAGGAGT
30     VH01023:1:AAC2L5HM5:1:1101:66214:3650:AAGACCTGTGACTACTTAGGCTGAGA
⋮      ⋮
158420 VH01023:1:AAC2L5HM5:1:2504:40518:22109:CGAACATGTCTGCGGTCACAGGTCTT
158421 VH01023:1:AAC2L5HM5:1:2505:54947:47930:AGCCTAATCCTATTCACTATAGCGTC
158422 VH01023:1:AAC2L5HM5:1:2506:46445:27769:CCACGGATCAGTGTTGCGGTGACCTA
158423 VH01023:1:AAC2L5HM5:1:2506:68903:30344:TTATGCTTCCTTCAATCGCTAAGTCC
158424 VH01023:1:AAC2L5HM5:1:2506:49039:31536:TGAGCATGTCGCTTCTCTCGGGTTTT
158425 VH01023:1:AAC2L5HM5:1:2506:48358:53723:ATCATGGTCTTGTTTGCGATCGACGG
158426 VH01023:1:AAC2L5HM5:1:2507:26184:46473:GGGAGATCAAACCCATACCCTCCCCG
158427 VH01023:1:AAC2L5HM5:1:2508:71573:11091:CAAGGCCGTACTTAGCAGACGCTGGG
158428 VH01023:1:AAC2L5HM5:1:2508:46350:16884:GTCACGGAGAATTCCCCTTTCCATAA
158429 VH01023:1:AAC2L5HM5:1:2508:50497:29890:TGGCCAGGTACCGTTATCCGTCTGAA
158430 VH01023:1:AAC2L5HM5:1:2511:57295:23056:CTACATTAGTATCTCGGATCTGTTGC
158431 VH01023:1:AAC2L5HM5:1:2511:73712:23377:ACACTGAAGTCACGCCTCTGACCTTT
158432 VH01023:1:AAC2L5HM5:1:2511:33455:27845:CTACATTTCGTAGGTTCCTTCCGCGC
158433 VH01023:1:AAC2L5HM5:1:2511:19064:38295:GACCATTGCGTGGCCCACAAACTCTT
158434 VH01023:1:AAC2L5HM5:1:2601:13876:21636:CTGATCCTCTGTACGAGGTCAAAATT
158435 VH01023:1:AAC2L5HM5:1:2602:54190:22980:AGAGCTTGTAGTAGTAAAAAATGCGA
158436 VH01023:1:AAC2L5HM5:1:2602:59946:29151:CCTAAAGAGGCCATAGCTGGCAATCG
158437 VH01023:1:AAC2L5HM5:1:2603:52107:16240:GCTGCGACAGCCAGAACCTAGTCTTT
158438 VH01023:1:AAC2L5HM5:1:2603:8366:20670:CTAGTGACACCAGATTGTATCATCCC
158439 VH01023:1:AAC2L5HM5:1:2603:42639:52398:GGCGTGTGTCGTGGCTTTAATGAGCA
158440 VH01023:1:AAC2L5HM5:1:2604:67653:14858:TTCTCCTCACAGCCCACTTCTATTAC
158441 VH01023:1:AAC2L5HM5:1:2604:29006:45659:AGCTCCTAGCGATGACGTTGGGACCT
158442 VH01023:1:AAC2L5HM5:1:2605:60022:11015:ATTTCTGGTGTTAAGAGGCTTTAAGT
158443 VH01023:1:AAC2L5HM5:1:2607:61991:22715:ACCGTAACAATCTGCACGCGCCCTAG
158444 VH01023:1:AAC2L5HM5:1:2608:17531:5714:CAAGATCTCGCTTGTCCCAACCGGTG
158445 VH01023:1:AAC2L5HM5:1:2608:28949:10693:GGGCATCTCCGCTGTTACTGTGGATT
158446 VH01023:1:AAC2L5HM5:1:2610:20030:14309:CATATGGAGGACTGGTAGAACTAAAC
158447 VH01023:1:AAC2L5HM5:1:2610:41105:53629:GCCTCTAAGCATCATCGGCATTAGCC
158448 VH01023:1:AAC2L5HM5:1:2611:56973:10845:GAGACCATCCGGGTGTACGTAATTAG
158449 VH01023:1:AAC2L5HM5:1:2611:44779:33524:GCGCCGACACGCCAGTTTTACTCTGC
       name                                                              flag
1      VH01023:1:AAC2L5HM5:1:1101:20882:1038:GTACACCAGTTCGCATCCCACTGACC  16
2      VH01023:1:AAC2L5HM5:1:1101:60552:1473:GAACCTACAAGGACTGCTCTAAGGGG  16
3      VH01023:1:AAC2L5HM5:1:1101:47032:1511:CGAGCACTCTCTTGATTGATTTACAT  16
4      VH01023:1:AAC2L5HM5:1:1101:21507:1587:CGAGCACTCTCTTGATGTAGCAGCTA  16
5      VH01023:1:AAC2L5HM5:1:1101:47752:1625:CTACACCAGTTCGCATCCAACGTATG  16
6      VH01023:1:AAC2L5HM5:1:1101:51955:1663:GTCCTCATCGGTGTCGTGTGTGTACA  16
7      VH01023:1:AAC2L5HM5:1:1101:49759:1966:ATCGAGTTCGACAGCCATGTGAGCCG  16
8      VH01023:1:AAC2L5HM5:1:1101:62824:1966:GATCGCGGTTAAAGTGTGATACCAGC  16
9      VH01023:1:AAC2L5HM5:1:1101:56481:2022:GTGAAGGAGCAAATCAGTCAGGCAGT  16
10     VH01023:1:AAC2L5HM5:1:1101:42942:2041:ATCGAGTTCGACAGCCGGACCGCTCG  16
11     VH01023:1:AAC2L5HM5:1:1101:56424:2117:GTGAAGGAGCAAATCAGTCAGGCAGT  16
12     VH01023:1:AAC2L5HM5:1:1101:33683:2136:ATCGAGTTCGACAGCCCTAATGCTTC  16
13     VH01023:1:AAC2L5HM5:1:1101:38682:2136:CCTTACGGTTGGACCCCACTCTTGCA  16
14     VH01023:1:AAC2L5HM5:1:1101:34648:2193:CTACACCAGTTCGCATATTCATCACA  16
15     VH01023:1:AAC2L5HM5:1:1101:21053:2268:GGCGACTCACTATCTTGGCCCCAGTA  16
16     VH01023:1:AAC2L5HM5:1:1101:26468:2306:CTACACCAGTTCGCATGCGTCGCTCT  16
17     VH01023:1:AAC2L5HM5:1:1101:26828:2401:GGCGACTCACTATCTTGCAACAGCGA  16
18     VH01023:1:AAC2L5HM5:1:1101:34667:2515:GATCTAGCAGACAAATTACAGTCCCG  16
19     VH01023:1:AAC2L5HM5:1:1101:28513:2571:ATCGAGTTCGACAGCCTACAGGGATA  16
20     VH01023:1:AAC2L5HM5:1:1101:26298:2704:TGGCCAGCATCACGTATGTTTCATTC  16
21     VH01023:1:AAC2L5HM5:1:1101:17000:2799:CGAGCACTCTCTTGATGTAGCAGCTA  16
22     VH01023:1:AAC2L5HM5:1:1101:44911:2799:GATTCAGGTGATGATAGCCGACAGCC  16
23     VH01023:1:AAC2L5HM5:1:1101:42374:2836:CTACACCAGTTCGCATGGCATAACGG  16
24     VH01023:1:AAC2L5HM5:1:1101:59927:3120:TCAGGTAGTAGGGACTTGCCATCTGG   0
25     VH01023:1:AAC2L5HM5:1:1101:26090:3139:GGCGACTCACTATCTTGCAACAGCGA  16
26     VH01023:1:AAC2L5HM5:1:1101:48945:3272:CAAGGCCCACCGAATTTATACGAATC  16
27     VH01023:1:AAC2L5HM5:1:1101:39041:3329:GGGTTGCCAGTAACGGTAACGGGTCG  16
28     VH01023:1:AAC2L5HM5:1:1101:22302:3480:TGGCCAGCATCACGTACATTACATCA  16
29     VH01023:1:AAC2L5HM5:1:1101:35860:3594:CATTATCGTATATCCGAGGGAGGAGT  16
30     VH01023:1:AAC2L5HM5:1:1101:66214:3650:AAGACCTGTGACTACTTAGGCTGAGA  16
⋮      ⋮                                                                 ⋮
158420 VH01023:1:AAC2L5HM5:1:2504:40518:22109:CGAACATGTCTGCGGTCACAGGTCTT 2064
158421 VH01023:1:AAC2L5HM5:1:2505:54947:47930:AGCCTAATCCTATTCACTATAGCGTC 2064
158422 VH01023:1:AAC2L5HM5:1:2506:46445:27769:CCACGGATCAGTGTTGCGGTGACCTA 2064
158423 VH01023:1:AAC2L5HM5:1:2506:68903:30344:TTATGCTTCCTTCAATCGCTAAGTCC 2064
158424 VH01023:1:AAC2L5HM5:1:2506:49039:31536:TGAGCATGTCGCTTCTCTCGGGTTTT 2048
158425 VH01023:1:AAC2L5HM5:1:2506:48358:53723:ATCATGGTCTTGTTTGCGATCGACGG 2048
158426 VH01023:1:AAC2L5HM5:1:2507:26184:46473:GGGAGATCAAACCCATACCCTCCCCG    0
158427 VH01023:1:AAC2L5HM5:1:2508:71573:11091:CAAGGCCGTACTTAGCAGACGCTGGG 2064
158428 VH01023:1:AAC2L5HM5:1:2508:46350:16884:GTCACGGAGAATTCCCCTTTCCATAA 2048
158429 VH01023:1:AAC2L5HM5:1:2508:50497:29890:TGGCCAGGTACCGTTATCCGTCTGAA 2064
158430 VH01023:1:AAC2L5HM5:1:2511:57295:23056:CTACATTAGTATCTCGGATCTGTTGC 2064
158431 VH01023:1:AAC2L5HM5:1:2511:73712:23377:ACACTGAAGTCACGCCTCTGACCTTT 2064
158432 VH01023:1:AAC2L5HM5:1:2511:33455:27845:CTACATTTCGTAGGTTCCTTCCGCGC 2064
158433 VH01023:1:AAC2L5HM5:1:2511:19064:38295:GACCATTGCGTGGCCCACAAACTCTT 2064
158434 VH01023:1:AAC2L5HM5:1:2601:13876:21636:CTGATCCTCTGTACGAGGTCAAAATT 2064
158435 VH01023:1:AAC2L5HM5:1:2602:54190:22980:AGAGCTTGTAGTAGTAAAAAATGCGA 2064
158436 VH01023:1:AAC2L5HM5:1:2602:59946:29151:CCTAAAGAGGCCATAGCTGGCAATCG 2064
158437 VH01023:1:AAC2L5HM5:1:2603:52107:16240:GCTGCGACAGCCAGAACCTAGTCTTT 2064
158438 VH01023:1:AAC2L5HM5:1:2603:8366:20670:CTAGTGACACCAGATTGTATCATCCC  2064
158439 VH01023:1:AAC2L5HM5:1:2603:42639:52398:GGCGTGTGTCGTGGCTTTAATGAGCA 2064
158440 VH01023:1:AAC2L5HM5:1:2604:67653:14858:TTCTCCTCACAGCCCACTTCTATTAC 2064
158441 VH01023:1:AAC2L5HM5:1:2604:29006:45659:AGCTCCTAGCGATGACGTTGGGACCT 2064
158442 VH01023:1:AAC2L5HM5:1:2605:60022:11015:ATTTCTGGTGTTAAGAGGCTTTAAGT 2064
158443 VH01023:1:AAC2L5HM5:1:2607:61991:22715:ACCGTAACAATCTGCACGCGCCCTAG 2064
158444 VH01023:1:AAC2L5HM5:1:2608:17531:5714:CAAGATCTCGCTTGTCCCAACCGGTG  2064
158445 VH01023:1:AAC2L5HM5:1:2608:28949:10693:GGGCATCTCCGCTGTTACTGTGGATT 2064
158446 VH01023:1:AAC2L5HM5:1:2610:20030:14309:CATATGGAGGACTGGTAGAACTAAAC 2064
158447 VH01023:1:AAC2L5HM5:1:2610:41105:53629:GCCTCTAAGCATCATCGGCATTAGCC 2064
158448 VH01023:1:AAC2L5HM5:1:2611:56973:10845:GAGACCATCCGGGTGTACGTAATTAG 2064
158449 VH01023:1:AAC2L5HM5:1:2611:44779:33524:GCGCCGACACGCCAGTTTTACTCTGC 2064
       ref_pos map_quality cigar         next_ref_name next_ref_pos length
1       557    60          89M           *             0            0
2      1971    60          89M           *             0            0
3      7227    60          89M           *             0            0
4      6160    60          90M           *             0            0
5      5752    60          90M           *             0            0
6      3052    60          89M           *             0            0
7      6493    60          89M           *             0            0
8      1855    58          90M           *             0            0
9      6151    60          90M           *             0            0
10     6850    57          90M           *             0            0
11     6151    60          90M           *             0            0
12     5795    60          89M           *             0            0
13     1914    60          90M           *             0            0
14     1562    60          90M           *             0            0
15     2426    60          90M           *             0            0
16     6062    60          90M           *             0            0
17     6835    60          90M           *             0            0
18     5572    60          90M           *             0            0
19     5867    60          90M           *             0            0
20     1343    60          89M           *             0            0
21     6160    60          90M           *             0            0
22     7316    60          90M           *             0            0
23     7211    60          90M           *             0            0
24     5071    60          87M           *             0            0
25     6835    60          90M           *             0            0
26     6083    60          90M           *             0            0
27     1800    60          90M           *             0            0
28     4550    60          90M           *             0            0
29     5455    60          90M           *             0            0
30     6037    60          90M           *             0            0
⋮      ⋮       ⋮           ⋮             ⋮             ⋮            ⋮
158420 7411    56          42H48M        *             0            0
158421 7411    60          48M42H        *             0            0
158422 7411    60          48M42H        *             0            0
158423 7411    57          48M42H        *             0            0
158424 7411    56          40H49M        *             0            0
158425 7411    60          41H48M        *             0            0
158426 7409    57          2S31M2I19M35S *             0            0
158427 7411    60          48M42H        *             0            0
158428 7411    60          41H48M        *             0            0
158429 7411    57          4H48M37H      *             0            0
158430 7411    60          48M42H        *             0            0
158431 7411    60          48M42H        *             0            0
158432 7411    57          48M42H        *             0            0
158433 7411    57          48M42H        *             0            0
158434 7411    60          48M42H        *             0            0
158435 7411    56          34H48M8H      *             0            0
158436 7411    57          48M42H        *             0            0
158437 7411    60          42H48M        *             0            0
158438 7411    60          48M42H        *             0            0
158439 7411    57          48M42H        *             0            0
158440 7411    60          3H48M39H      *             0            0
158441 7411    60          48M42H        *             0            0
158442 7411    57          7H48M35H      *             0            0
158443 7411    57          48M42H        *             0            0
158444 7411    57          48M42H        *             0            0
158445 7411    60          48M42H        *             0            0
158446 7411    57          4H48M38H      *             0            0
158447 7411    57          48M42H        *             0            0
158448 7411    60          48M42H        *             0            0
158449 7411    60          48M42H        *             0            0
       seq
1      GTCCGTGTTTCCTTTTATTCCTATATTGGCTGCTTATGGAGACAATCAAAGAGTTGTTACCATATAGCTATTGGATTGGCCATCCGGTG
2      TCAGAGCTGACCCTGGACGAAGTGGGCCATGGCAGTCCACCTTGTTGGGCCAGTTGTGCGGGTACTACACCCAATGGTCAGGATCACTG
3      ATGAAAAATTTGTGAGTGCAATCAGATCAGTTCCAATTGGAAAAGCATTGGCTATACCAAATTATGAGAATCTGAGAAGAAATTGGCTC
4      CAAGGAGGCGGCCTTACATTATGCCAACCAACTCAAGCAGTTAGATATCAAGACCACCAAGATGAGCATGGAGGATGCATGTTACGGCAC
5      GTATGGGTTTTTGAACCTTAGTGGTAAGCCCACTCACAGGACTATGATGTACAATTTCCCAACAAAAGCAGGACAGTGTGGTGGTGTTGT
6      TTATGACGGGTATCCCACATTCGGTGAACACAAACAGGAGAAAGACCTTGAATACGGGGCATGCCCAAACAACATGATGGGTACGTTCT
7      GTACTTGAGAATGACATTTGGGCACCTTTATGAAGCTTTCCACGCCAATCCAGGTACAATCACTGGTTCAGCTGTTGGGTGTAACCCAG
8      CCAGGTGGAGACCATTTTAGAGGTCAACAATGTACCTACGAATGCCACTAGCTTAATGGAGAGACTGCGCTTCCCGGTCTCAGCTCAAGC
9      CGAGTTTGTCAAGGAGGCGGCCTTACATTATGCCAACCAACTCAAGCAGTTAGATATCAAGACCACCAAGATGAGCATGGAGGATGCATG
10     CATTATTAGAACACTCCTGATTAAAACATTCAAAGGGATAGATCTAGATGAACTGAACATGGTGGCCTATGGGGATGATGTGTTGGCTAG
11     CGAGTTAGTCAAGGAGGCGGCCTTACATTATGCCAACCAACTCAAGCAGTTAGATATCAAGACCACCAAGATGAGCATGGAGGATGCATG
12     ATGATGTACAATTTCCCAACAAAAGCAGGACAGTGTGGTGGTGTTGTGACTGCCGTGGGTAAAGTGATTGGGATCCACATTGGTGGCAA
13     AGAGACTGCGCTTCCCGGTCTCAGCTCAAGCCGGGAAAGGTGAGCTATGTGCAGTGTTCAGAGCTGACCCTGGACGAAGTGGGCCATGGC
14     GATTCTGCCTTGAACCATTGTAACTTTGGTCTGCTGGTTGTGCCTATTAGCCCGTTAGATTATGACCAAGGTGCGACGCCAGTGATCCCC
15     ACAGGCACTATCCAGGGAGATAGGGTGGCAGATGTGATTGAGAGTTCTATAGGGGACAGTGTGAGCAGAGCCCTCACCCGAGCTCTACCG
16     GTGCTGACTAGTAAAGACCCAAGGCTGGAAGTTGACTTTGAACAGGCTCTTTTTTCAAAATACGTGGGGAACACGCTTCATGAACCCGAC
17     GATGATCAACAATATCATTATTAGAACACTCCTGATTAAAACATTCAAAGGGATAGATCTAGATGAACTGAACATGGTGGCCTACGGGGA
18     GGTAGTAGACGAACAAGGGGTTAACTTAGAGCTCACACTGGTAACGCTTGATACTAACGAAAAATTTAGAGACATCACAAGATTCATACC
19     ATCCACATTGGTGGCAACGGTAGGCAAGGTTTCTGCGCTGCCCTGAAGAGGGGATACTTTTGCAGTGAACAAGGTGAGATCCAATGGATG
20     GTCATTGGGACAGTGGCAGGTGGCACAGGGACGGAGGATAGCCACCCCCCTTATAAGCAGACTCAACCCGGTGCTGATGGCTTCGAATT
21     CAAGGAGGCGGCCTTACATTATGCCAACCAACTCAAGCAGTTAGATATCAAGACCACCAAGATGAGCATGGAGGATGCATGTTACGGCAC
22     GAATTGTTTTAAATTTACAGTTTGTAACTGAACCCCACCAGTAATCTGGTCGCGTTAATGACTGGTGGGGGTAAATTTGTTATAACCAGA
23     AACGGGAAAGAGGAGTATGAAAAATTTGTGAGTGCAATCAGATCAGTTCCAATTGGAAAAGCATTGGCTATACCAAATTATGAGAATCTG
24     CCCTAAATTTAGACCAATAAGGATTAGCTTAGAGGAGAAGCCCGCACCTGATGCTATTAGTGACTTATTAGCTAGTGTTGATAGTGA
25     GATGATCAACAATATCATTATTAGAACACTCCTGATTAAAACATTCAAAGGGATAGATCTAGATGAACTGAACATGGTGGCCTACGGGGA
26     AGGCTGGAAGTTGACTTTGAACAGGCTCTTTTTTCAAAATACGTGGGGAACACGCTTCATGAACCCGACGAGTTTGTCAAGGAGGCGGCC
27     ACCCCACCCCGTGTATCCATATACCCGGTGAAGTTAGAAACTTGCTAGAGCTATGCCAGGTGGAGACCATTTTAGAGGTCAACAATGTAC
28     CCTCCAGACCCAGACCACTTTGACGGATACAAACAACAGATCGTCACTGTTATGGACGACCTATGCCAAAACCCAGACGGGAAAGACATG
29     GGGCCACTTTACAATGTTAGGAGTGCGAGACCGCTTGGCTGTGCTCCCCAGACACTCCCAACCAGGAAAGACCATCTGGGTTGAACACAA
30     GTTCGAAGGCACTAAAGAGCCAGCAGTGCTGACTAGTAAAGACCCAAGGCTGGAAGTTGACTTTGAACAGGCTCTTTTTTCAAAATACGT
⋮      ⋮
158420 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158421 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158422 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158423 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158424 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158425 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158426 AGGCAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTAAAAAAAAAAAAAAAAAAAAAAAAACACCCAAAAAAAAAAAAAAAAAAAAAACA
158427 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158428 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158429 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158430 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158431 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158432 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158433 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158434 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158435 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158436 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158437 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158438 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158439 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158440 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158441 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158442 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158443 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158444 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158445 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158446 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158447 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158448 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
158449 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
       qual
1      CCCCCCCCCC;CC;C--C;-CCCC-C--;;C-;;-C-C;-CCCCCC;CCCCC;;CC;C;CCCC;;CCCCCC;-C-;CC-;-C-C--CCC
2      CCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCC
3      CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
4      CCCCCCCCCCCCCCCCC;CCCCCCCCCC;CCCCCCCCCC-CCCCCCCC;C-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
5      CCCCCCC;CCC;C;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
6      CCCCCCCC;CCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCCCCCC;
7      CCCCC-CCCCCCCCCCCCCCCCCCCC-CCCCCCCC;CCCCCCC-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCC;;CCCC
8      CCCCCCCCCCCCC;CCCCCCCCCCCCCCC-C;CC-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CC;CC-CCCCCCCCCCCC
9      CCCCCCCCCCCCC;CCC;CCCC--CC-CCCC;CCC;CCCCCCC-C-CC-;C;CCCC-C-CCCCCCCC--CCCCCCCCCCCCCCCCC;CCC
10     CCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCC;CCCCCCC
11     CCCC-C-CCCCCCCCCCCCCCCC;CCC;CCCCCCC;CCC;C;CCC-;C;CC;CCCC;;--CCCCCCC-CCCCCCCCCCCCCCCCCCCCCC
12     CCCCCCCCCCCCCCCCCCCCCCC;;CCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCC;CCCCCCCCCCC-CCC;CCCCC
13     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
14     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCC
15     CCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCC-CCCCCCCCCCCCCCCC;CC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCC
16     CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CC
17     CCCCC-CCC;CCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCC;C
18     C-CCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCC;CCCCCCC

In [ ]:
PV=allreadsdir("/hpcdata/lvd_qve/Projects/PTD_StrandSpecificCounting_scRNAseq/81123_SCISSORS_FreshAnalysis/PV_Rep")    
readr::write_rds(PV,file = "PV_SCISSORS.rds")

In [ ]:
singles=unique(PV$datalabel)[c(11,3,4,5,6)]
doubles=unique(PV$datalabel)[c(7,8,9,10)]
IRES=unique(PV$datalabel)[c(11,13,1,2,6,12,14,15)]

singles
doubles
IRES

In [ ]:
PVrep=computeRepIndex(PV,"RepliconNoInsert")
PVgfp=computeRepIndex(PV,"eGFP")
PVruby=computeRepIndex(PV,"mRuby3")

In [ ]:
PVgfp[,c("meanRI","sdRI"):=list(mean(na.omit(repIndex)),sd(na.omit(repIndex))),by=datalabel]

In [ ]:
ggplot(PVgfp)+
    geom_point(aes(readSum,repIndex),alpha=ifelse(PVgfp$readSum>CUTOFF,0.4,0.02))+THEME

In [ ]:
ggplot(EV71DT[readSum>CUTOFF])+
    geom_point(aes(log10(Negative/(1+Positive)),log10(repIndex)))+THEME

In [ ]:
virus<-rbindlist(list(CVBDT,EV71DT))
allDTs<-rbindlist(list(PVrep,PVgfp,PVruby))[DataTable!="RepliconNoInsert"]

In [ ]:
EV71DT

In [ ]:
viosV<-ggplot(virus[readSum>CUTOFF])+THEME+ylab("Replication Index")+xlab("Virus")+
    geom_violin(aes(fill=DataTable,datalabel,repIndex))+
    geom_boxplot(alpha=0.4,width=0.2,aes(datalabel,repIndex))+
    scale_fill_brewer("Virus",palette = "Dark2")+
    theme(axis.text.x = element_text(hjust=1,angle=90))

viosPV<-ggplot(allDTs[readSum>CUTOFF&datalabel%in%c(singles,doubles)])+scale_y_log10()+THEME+ylab("Replication Index")+xlab("Replicon")+
    geom_violin(aes(fill=DataTable,paste(factor(datalabel,levels = c('/WT_GFP','/RFPMutPol','/WT_GFP_RFPMutPol','/RFP_488P','/WT_GFP_RFP_488P','/RFP_C109S','/WT_GFP_RFP_C109S','/RFP_D177A','/WT_GFP_RFP_D177A')),DataTable),repIndex))+
    geom_boxplot(alpha=0.4,width=0.2,aes(fill=DataTable,paste(factor(datalabel,levels = c('/WT_GFP','/RFPMutPol','/WT_GFP_RFPMutPol','/RFP_488P','/WT_GFP_RFP_488P','/RFP_C109S','/WT_GFP_RFP_C109S','/RFP_D177A','/WT_GFP_RFP_D177A')),DataTable),repIndex))+
    scale_fill_brewer("Replicon",palette = "Set1")+
    theme(axis.text.x = element_text(hjust = 1,angle=90))

viosPVsingle<-ggplot(allDTs[readSum>CUTOFF&datalabel%in%singles])+scale_y_log10()+THEME+ylab("Replication Index")+xlab("Replicon")+
    geom_violin(aes(fill=datalabel,reorder(datalabel,repIndex,max),repIndex))+
    geom_boxplot(alpha=0.4,width=0.2,aes(datalabel,repIndex))+
    scale_fill_brewer("Replicon",palette = "Set1")+
                 facet_wrap(~DataTable)+theme(axis.text.x = element_text(hjust = 1,angle=90))

viosPVdouble<-ggplot(allDTs[readSum>CUTOFF&datalabel%in%doubles])+scale_y_log10()+THEME+ylab("Replication Index")+xlab("Replicon")+
    geom_violin(aes(fill=datalabel,reorder(datalabel,repIndex,max),repIndex))+
    geom_boxplot(alpha=0.4,width=0.2,aes(datalabel,repIndex))+
    scale_fill_brewer("Replicon",palette = "Dark2")+
                 facet_wrap(~DataTable)+theme(axis.text.x = element_text(hjust = 1,angle=90))

viosPVires<-ggplot(allDTs[readSum>CUTOFF&datalabel%in%IRES])+scale_y_log10()+THEME+ylab("Replication Index")+xlab("Replicon")+
    geom_violin(aes(fill=factor(datalabel,levels=c('/WT_IRES_GFP','/WT_GFP','/RFPMutPol','/WT_IRES_mRuby3_MutPol','/Del_IRES_mRuby3','/WT_IRES_mRuby3_MutPol_WT_IRES_GFP','/Del_IRES_mRuby3_MutPol','/WT_IRES_GFP_Del_IRES_mRuby3')),factor(datalabel,levels=c('/WT_IRES_GFP','/WT_GFP','/RFPMutPol','/WT_IRES_mRuby3_MutPol','/Del_IRES_mRuby3','/WT_IRES_mRuby3_MutPol_WT_IRES_GFP','/Del_IRES_mRuby3_MutPol','/WT_IRES_GFP_Del_IRES_mRuby3')),repIndex))+
    geom_boxplot(alpha=0.4,width=0.2,aes(datalabel,repIndex))+
    scale_fill_brewer("Replicon",palette = "Paired")+
                 facet_wrap(~DataTable)+theme(axis.text.x = element_text(hjust = 1,angle=90))

ggsave(filename = "vios_V.pdf",viosV,width=8,height=6)
ggsave(filename = "vios_PV.pdf",viosPV,width=9,height=6)
ggsave(filename = "vios_Vsingles.pdf",viosPVsingle,width=6,height=6)
ggsave(filename = "vios_Vdoubles.pdf",viosPVdouble,width=8,height=6)
ggsave(filename = "vios_PVires.pdf",viosPVires,width=8,height=6)

In [ ]:
merge_GR<-merge.data.table(fill=0,PVgfp[readSum>CUTOFF],PVruby[readSum>CUTOFF],all = T,by = c("CBC","sample","datalabel"),suffixes = c("G","R"))
merge_GR[is.na(merge_GR)]<-0

In [ ]:
ggplot(merge_GR[(readSumG>CUTOFF)|(readSumR>CUTOFF)&(datalabel%in%doubles)],aes(repIndexG,repIndexR,col=datalabel))+
    geom_point()+#scale_x_log10()+scale_y_log10()+
    geom_smooth(method = 'lm')+THEME+coord_fixed()#+facet_grid(~datalabel)
ggplot(merge_GR[(readSumG>CUTOFF)|(readSumR>CUTOFF)&(datalabel%in%doubles)],aes(repIndexG,repIndexR,col=datalabel))+
    geom_point()+
    geom_smooth(method = 'gam')+THEME+coord_fixed()#+facet_grid(~datalabel)

In [ ]:
bincounts<-merge_GR[,as.data.table(table(ifelse(repIndexR>0.035,"R+","R-"),ifelse(repIndexG>0.035,"G+","G-"))),by=c("datalabel")]

bincounts[,normCellN:=(N/sum(N)),by=datalabel]
unique(bincounts$datalabel)

IRESsamples=c('/WT_IRES_GFP',
'/RFPMutPol',
'/WT_IRES_mRuby3_MutPol',
'/WT_IRES_mRuby3_MutPol_WT_IRES_GFP',
'/Del_IRES_mRuby3',
'/WT_IRES_GFP_Del_IRES_mRuby3',
'/Del_IRES_mRuby3_MutPol')

mutSamples=c('/WT_GFP',
  '/RFPMutPol',
  '/WT_GFP_RFPMutPol',
'/RFP_488P',
'/WT_GFP_RFP_488P',
'/RFP_C109S',
'/WT_GFP_RFP_C109S',
 '/RFP_D177A',
'/WT_GFP_RFP_D177A')

library(cowplot)
cowplot::plot_grid(nrow = 2,align = "hv",
    ggplot(bincounts[datalabel%in%IRESsamples])+ggtitle("IRES")+xlab("Infected Cell Bin")+ylab("Condition")+
    geom_point(aes(paste(V1,V2),factor(datalabel,levels = IRESsamples),col=paste(V1,V2),size=normCellN))+scale_color_manual("Cell Bin",values = c("grey","darkgreen","darkred","goldenrod"))+THEME,

    ggplot(bincounts[datalabel%in%mutSamples])+ggtitle("Mutants")+xlab("Infected Cell Bin")+ylab("Condition")+
    geom_point(aes(paste(V1,V2),factor(datalabel,levels = mutSamples),col=paste(V1,V2),size=normCellN))+scale_color_manual("Cell Bin",values = c("grey","darkgreen","darkred","goldenrod"))+THEME
)
ggplot(bincounts)+ggtitle("Counts")+
geom_point(aes(paste(V1,V2),datalabel,col=paste(V1,V2),size=N))+scale_color_manual("Cell Bin",values = c("grey","darkgreen","darkred","goldenrod"))+THEME

In [ ]:
ggplot(merge_GR[datalabel%in%doubles],aes(repIndexG,repIndexR,col=datalabel))+
    geom_point()+
    geom_smooth(method = 'lm')+THEME
ggplot(merge_GR[datalabel%in%doubles],aes(repIndexG,repIndexR,col=datalabel))+
    geom_point()+
    geom_smooth(method = 'gam')+THEME


ggplot(merge_GR[datalabel%in%doubles],aes(NegativeG,PositiveG,col=datalabel))+
    geom_point()+
    geom_smooth(method = 'glm')+THEME

In [3]:
dAR[,negpos:=(Negative+1)/(Positive+1)]
ARF<-melt(dAR,id.vars = c("CBC","sample","datalabel","region","negpos"))
allreadsre<-dcast.data.table(ARF,CBC+datalabel+negpos+variable~region)
#print(allreadsre)
allreadsre[,mRuby3:=ifelse(is.na(mRuby3),0,mRuby3),by=CBC]
allreadsre[,eGFP:=ifelse(is.na(eGFP),0,eGFP),by=CBC]
allreadsre[,RepliconNoInsert:=ifelse(is.na(RepliconNoInsert),0,RepliconNoInsert),by=CBC]

ERROR: Error in eval(expr, envir, enclos): object 'dAR' not found

In [ ]:
ggsave( "count_histogram.pdf",width = 4,height=10,
    ggplot(allreadsre)+
    geom_histogram(aes(eGFP+1),fill="darkgreen",alpha=.4)+
    geom_histogram(aes(mRuby3+1),fill="darkred",alpha=.4)+
    facet_grid(datalabel~variable,scales = "free_y")+
    scale_x_log10(limits=c(2,NA))
)


ggplot(allreadsre)+
geom_histogram(aes(eGFP+1),fill="darkgreen",alpha=.4)+
geom_histogram(aes(mRuby3+1),fill="darkred",alpha=.4)+
facet_grid(variable~datalabel,scales = "free_y")+
scale_x_log10(limits=c(2,NA))

In [ ]:
ggplot(allreadsre[])+
geom_point(aes(eGFP,log10(negpos)),col="darkgreen")+
geom_point(aes(mRuby3,log10(negpos)),col="darkred")+
facet_grid(datalabel~variable)+
coord_cartesian(xlim=c(0,1000))+
xlab("read counts")

In [ ]:
ggplot(allreadsre[(eGFP>1)|(mRuby3>1)])+
geom_violin(aes(log10(eGFP+1),datalabel),col="darkgreen")+
geom_violin(aes(log10(mRuby3+1),datalabel),col="darkred")+
geom_boxplot(aes(log10(eGFP+1),datalabel),col="darkgreen")+
geom_boxplot(aes(log10(mRuby3+1),datalabel),col="darkred")+
facet_grid(variable~eGFP>10)

In [ ]:
dAR[CBC%in%dAR[(Positive>10)&(region!='RepliconNoInsert'),nrow(.SD),by=list(sample,CBC)][V1==2,]$CBC]

In [ ]:
dAR

In [ ]:
filtered<-dAR[datalabel=="WT_IRES_GFP"&region=="eGFP"]

dAR[Negative>10,paste(round(median(negpos), digits=2),"+/-",round(mad(negpos),digits = 2)),by=c("datalabel","region"),][region%in%c("eGFP","mRuby3")]

medians=dAR[Negative>10,list(median=round(median(negpos), digits=2),lowerq=round(sort(negpos)[0.25*length(negpos)],digits = 2),upperq=round(sort(negpos)[0.75*length(negpos)],digits = 2)),by=c("datalabel","region"),][region%in%c("eGFP","mRuby3")]
pdf("pointrange_replicationRate_Scissors.pdf")
ggplot(medians[-9])+
    scale_color_manual("Reporter",values = c("darkgreen","darkred"))+
    geom_pointrange(aes(factor(datalabel,levels = c("WT_IRES_GFP","Del_IRES_mRuby3","WT_IRES_mRuby3_MutPol","Del_IRES_mRuby3_MutPol","WT_IRES_GFP_Del_IRES_mRuby3","WT_IRES_mRuby3_MutPol_WT_IRES_GFP")),y=median,ymax=upperq, ymin=lowerq,col=region), lwd=1)+
    theme(axis.text.x = element_text(angle=90))+ylab("Negative:Postive RNA Ratio\nReplication Rate")+xlab("Transfected Replicon Construct")
dev.off()

In [ ]:
dAR[region%in%c("mRuby3","eGFP"),]#ggplot()+geom_point(aes(Negative,Positive))+scale_x_log10()+scale_y_log10()

In [ ]:
#ggplot(dAR)+
#    geom_point(aes(region,negpos))+
#    geom_segment(aes(x=region,xend=region,y=negpos,yend=negpos))


FILT=dAR[Positive>10&region%in%c("mRuby3","eGFP")]

ResFILT<-dcast.data.table(FILT,CBC+datalabel~region)
ResFILT
ggplot(ResFILT[datalabel%in%c("WT_IRES_mRuby3_MutPol_WT_IRES_GFP","WT_IRES_GFP_Del_IRES_mRuby3"),])+
geom_point(aes(eGFP,mRuby3,col=datalabel))+
geom_smooth(method = "lm",aes(eGFP,mRuby3,col=datalabel))

In [ ]:
DATA<-fread("./lab_share/Projects/PTD_StrandSpecificCounting_scRNAseq/CellRanger/WT_IRES_GFP/outs/analysis/umap/gene_expression_2_components/projection.csv")
DATA

DATA[,CBC:=strsplit(Barcode,split = "-")[[1]][1],by=Barcode]
DATAm<-merge.data.table(DATA,filtered,by="CBC")
ggplot(DATAm)+
geom_point(data=DATA,aes(`UMAP-1`,`UMAP-2`),cex=0.3)+
geom_point(aes(`UMAP-1`,`UMAP-2`,color=-log10(negpos)))+coord_fixed()+scale_color_viridis_c(direction = 1)

In [ ]:
DATA<-fread("./lab_share/Projects/PTD_StrandSpecificCounting_scRNAseq/CellRanger/WT_IRES_GFP/outs/analysis/tsne/gene_expression_2_components//projection.csv")
DATA[,CBC:=strsplit(Barcode,split = "-")[[1]][1],by=Barcode]
DATAm<-merge.data.table(DATA,filtered,by="CBC")
pdf("TSNE.pdf",width = 10,height=10)
ggplot(DATAm)+
geom_point(data=DATA,aes(`TSNE-1`,`TSNE-2`),cex=0.3)+
geom_point(aes(`TSNE-1`,`TSNE-2`,color=log10(negpos),size = Positive))+
scale_size_continuous("Viral Genome Count")+
coord_fixed()+
scale_color_viridis_c(direction = 1,"log10((-) to (+) Ratio)\n(Replication Rate)")
dev.off()

In [ ]:
ggplot(DATAm)+
geom_point(data=DATA,aes(`TSNE-1`,`TSNE-2`),cex=0.3)+
geom_point(aes(`TSNE-1`,`TSNE-2`,color=log10(negpos),size = Positive))+
scale_size_continuous("Viral Genome Count")+
coord_fixed()+
scale_color_viridis_c(direction = 1,"log10((-) to (+) Ratio)\n(Replication Rate)")